### ISSUE TITLE
Multiple handlers that extend AbstractCommandHandler in same project fails to startup

### ISSUE THREAD

**Issue by vahidhedayati** [mfarache/micronaut-cqrs-kafka#2]
Hi Mauricio 

I have made this commit to my version which is a similar expanded revision of your code:

https://github.com/vahidhedayati/micronaut-vuejs-cqrs/commit/390c3bd4eaa41eedb6f54d428223064712943db7

For some odd reason if I attempt to bring up to handlers - which from what I see should cause no issues and is essential to doing things that have further complexity than 1 object or 1 action as such.

```
Path Taken: $DataLoaderDefinition$Intercepted.hotelService --> HotelService.bus --> new BusImpl([CommandHandler handler])
at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:990)
        at hotel.write.cqrs.bus.$BusImplDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1494)
        at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1949)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1851)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1829)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:997)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1346)
        at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:714)
        at hotel.write.services.write.$HotelServiceDefinition.injectBean(Unknown Source)
        at hotel.write.services.write.$HotelServiceDefinition.build(Unknown Source)

```

I have now removed this other handler so app will startup - Due to limitation the main handler has been fudged to hand delete / update - it would have been more elegant to have a handler for each type of action.

At this point the error is really vague and not sure if this is a problem with how BusImpl class is written or if it is a deeper problem within micronauts.

Thoughts on matter much appreciated if it is micronaut then I can raise issue with them.

**Comment by vahidhedayati** [comment]
I am currently reworking all of this but hit a similar issue and may have been related to `@Primary` declaration missing from one of the two above.
